src/metrics/chainflip/gaugeRotationDuration.ts

We now only have 2 metrics, a counter which gets incremented by 1 at every block and measures the total duration of the rotation.
A second counter with different labels to measure the duration of each different stage.
These two counters gets resetted after the rotation completes.

simplified rotation duration (which was not working before)

---

src/metrics/chainflip/gaugeBroadcastRetryQueues.ts
src/metrics/chainflip/gaugeSwappingQueue.ts
src/metrics/chainflip/gaugeTssRetryQueues.ts
src/metrics/chainflip/index.ts
src/watchers/chainflip.ts

- Added few queue size metrics
- Removed restart in case of exception (ws reconnection automatically handled by substrate client)

added gauges to track queues size

---

src/metrics/chainflip/gaugePendingBroadcast.ts
src/metrics/chainflip/gaugeTssRetryQueues.ts
src/metrics/chainflip/index.ts
src/watchers/chainflip.ts

Changed the metric to scrape the amount of pending broadcasts which better represent the number of broadcasts currently being processed

changed broadcastRetryQueue to PendingBroadcast

---

config/berghain.json

Adding the stateChainGateway address to the wallets in the config so that we can have its FLIP balance exported as a metric

update config to include the stateChainGateway

---

src/metrics/chainflip/gaugeFeeDeficit.ts
src/metrics/chainflip/index.ts
src/watchers/chainflip.ts

Adde metric to track the fee deficit of the network, currently it has been added only for dot and eth since for btc is not trivial to get this info (when Martin is back will talk to him on how it can be done for btc)

added fee deficit metric

---

src/metrics/chainflip/gaugePendingRedemptions.ts

The storageItem PendingRedemptions was modified hence we need to update the logic to correctly read the new fields.

fix: RedemptionBalance

---

src/metrics/chainflip/gaugeAuthorities.ts
src/metrics/chainflip/gaugeWitnessChainTracking.ts
src/metrics/chainflip/gaugeWitnessCount.ts
src/watchers/chainflip.ts

Start all the request simultaneously to avoid "blocking" the other parts of the code.
If a request completes when we are already analyzing the next block we discard the result (only in case of chainTracking, for all the other extrinsics we are still reporting everything)

Fix witnessing count

---

src/metrics/chainflip/gaugePriceDelta.ts

Removed Math.round from labelAmount -> labelAmount doesn't need to be rounded (it can be a float, there is no point in rounding it and lose precision)

fix: remove rounding

---

src/metrics/chainflip/countEvents.ts

When an extrinsic fails we get back an index and an index error, these aren't very useful in understanding what the actual error is without having to go and check directly in the backend repo.
We create a mapping between the known error codes and the Human Readable version of the Error, adding it to the metadata field of the logs such that we can use that for alerting purposes.

add mapping for errors

---

src/metrics/eth/gaugeFlipBalance.ts
src/metrics/eth/index.ts
src/watchers/ethereum.ts

Add FLIP total supply metric (coming from the FLIP contract on eth)
We can now use this new metric and cf_total_flip_supply (coming from the state-chain) to check if the balance discrepancy is low enough (we update the total supply on eth once a day). This new alarm will fire if the discrepancy grow too much, meaning there could be some exploit going on which allows people to mint new FLIP only on ETH/state-chain

add FLIP totalSupply, queried from flip contract

---

src/metrics/chainflip/gatherGlobalValues.ts

Fixed a bug where we were using the vault key address instead of the aggKey address.

use the correct address to retrieve aggKey balance

---

.gitignore
config/berghain.json
src/metrics/chainflip/gaugeWitnessChainTracking.ts

fixed a bug introduced with refactoring:
- we want to process only the latest chaintracking (if 2 different updateStateChain extrinsic for the same chain are in the same block we'll only process the most recent one, where most recent means it has the highest block number)

fix bug -> properly assign the processed block number

---

src/metrics/chainflip/countEvents.ts
src/metrics/polkadot/countEvents.ts

initialize counters to 1 (the one use for alerting) -> counter not initialized aren't capture when using increase(), since their value before initialization is null and not defaulting to 0 (like you would expect)

Initialize counters value

---

src/metrics/chainflip/gaugeWitnessChainTracking.ts
src/metrics/chainflip/gaugeWitnessCount.ts

- Handle case when the result is "old" meaning we get back the witness count but the current block has moved forward and we don't care about the result anymore
- Add catching to the promises when they get rejected

fix: handle case when the result is "old" (previous block)

---

src/metrics/chainflip/gaugeWitnessCount.ts

Increase the window before deleting the metrics containing the list of failing validators so that we can properly reference them when alerting.
(40 -> 100 blocks)

Fix: increase liveness of "support" metrics

---

config/sisyphos.json
src/metrics/sol/gaugeDurableNonces.ts
src/watchers/solana.ts

Solana connection doesn't allow to use an endpoint with basic auth in it, it will fail to execute the request.
We handle the case such that if basic auth is used the Connection will be able to execute requests without failing.

pass basic auth through header

---

src/metrics/arb/countContractEvents.ts
src/metrics/chainflip/countEvents.ts
src/metrics/chainflip/eventsRotationInfo.ts
src/metrics/eth/countContractEvents.ts
src/metrics/polkadot/countEvents.ts

- Use Gauges when the metric is used for alerting -> we can set it to 0 as "initialization"
- Add broadcaster label to CCM/non-CCM broadcastAborted so that we can quickly determine which target chain was the broadcast for

switch to Gauge for metrics used for alerts

---

src/metrics/btc/gaugeBlockHeight.ts
src/metrics/chainflip/countEvents.ts
src/metrics/chainflip/gaugeSafeMode.ts
src/metrics/polkadot/gaugeBlockHeight.ts
src/utils/makeRpcRequest.ts
src/watchers/chainflip.ts
src/watchers/polkadot.ts

- Initialize label bitcoinIngressEgress:BoostedDepositLost to 0 for gauge cf_events_count (to avoid initial increment)
- add cf_safe_mode() which exposes if safe mode is enable or not (a label name is used to identify which safe mode we are talking about)
- use polling to query the last block height for dot like we do for other chain -> ws seems unreliable
- support api key for btc endpoints

feat: improvements

---

src/metrics/sol/startSubscription.ts

Reduce the liveness of `sol_tx_reverted` to 1m such that manually resolvable alert won't keep firing if resolved in the first 10m.

feat: reduce liveness of temporary metric

---

src/metrics/sol/startSubscription.ts

Added a separate metric to track TX reverted for solana such that we can separate normal tx from CCM tx

feat: create separate metrci for CCM solana tx reverted

---

src/metrics/chainflip/gaugeEpoch.ts
src/utils/makeRpcRequest.ts

Rename deprecated field `blocks_per_epoch` to `epoch_duration`

fix: rename deprecated field

---

src/metrics/chainflip/gaugeOraclePrices.ts
src/metrics/chainflip/gaugePriceDelta.ts
src/metrics/chainflip/gaugeValidatorStatus.ts
src/metrics/chainflip/index.ts
src/metrics/sol/gaugeTransactionsOutcome.ts
src/utils/customRpcSpecification.ts
src/utils/makeRpcRequest.ts
src/utils/utils.ts
src/watchers/chainflip.ts

Added 2 new metrics:
- `cf_oracle_price` -> expose the oracle price
- `cf_oracle_price_delta` -> expose the %difference of our oracle price compared to the index price (coingecko)
- Removed backup validators
- Fixed a bug while querying solana rotation tx

feat: add oraclePrices metrics

---

src/metrics/chainflip/gaugeDelegation.ts
src/metrics/chainflip/index.ts
src/utils/customRpcSpecification.ts
src/utils/makeRpcRequest.ts
src/watchers/chainflip.ts

Added new metrics to track delegation:
- current bond
- next bond
- difference between the two above
- number of new validators joining the set
- amount of flip delegated to an operator

feat: add delegation metrics
